name = "Pliers"
uuid = "4cb22d17-b64b-43a3-bccc-aaaac22c5b31"
version = "0.1.0"
authors = ["Mohamed Numair <mo7amednumair@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Serialization = "1.11.0"
Suppressor = "0.2.8"
