[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Pliers = "4cb22d17-b64b-43a3-bccc-aaaac22c5b31"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
